# This action updates assets files
name: Assets updater

on:
  # weekly
  schedule:
    - cron: '0 0 * * SUN'

  # manually
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  workingBranch: assets-updater-action

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Git config
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'

      - name: Prepare branch
        run: |
          count=($(git ls-remote --heads origin "$workingBranch" | wc))
          if [[ ${count[0]} -ne 0 ]]; then
            # Exists
            git fetch
            git checkout -b $workingBranch "origin/$workingBranch"
          else
            # Does not exist
            git checkout -b $workingBranch
            git push --set-upstream origin $workingBranch
          fi

      - name: ClearURLs catalog
        continue-on-error: true # just skip the file
        run: |
          bash ./.github/scripts/file-updater.sh $fileName $fileURL $filePath $hashURL
          git add "$filePath$fileName"
          git commit -m "
          $message
          
          File: $filePath$fileName
          Url: $fileURL
          Hash: $hashURL
          "
          
          git push
          echo "$fileName commited successfully"
        env:
          fileName: "data.minify.json"
          fileURL: "https://rules2.clearurls.xyz/data.minify.json"
          filePath: "./app/src/main/assets/"
          hashURL: "https://rules2.clearurls.xyz/rules.minify.hash"
          message: "ClearURLs catalog updated"

      - name: Pull request
        continue-on-error: true # ignore if the pr already exists
        run: |
          gh pr create --title 'Assets updated (automatic action)' --body 'One or more assets were updated.
          
          This is an automatic PR run from a [github action](../actions/workflows/assets-updater.yml)'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
