# This action will send a comment to the pr for download the built apk.
# Needs to be as a separate action, artifacts are not available on the action used to upload them
name: Comment Artifact URL on PR

on:
  workflow_run:
    workflows:
      - "Validate gradle build test"
    types:
      - "completed"

permissions:
  actions: read # need to read the artifacts url
  pull-requests: write # need to write the comment

jobs:
  comment-on-pr:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.pull_requests[0] != null
    runs-on: ubuntu-latest
    steps:

      - name: Post url to artifact
        timeout-minutes: 5
        env:
          GITHUB_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          PREVIOUS_JOB_ID: ${{ github.event.workflow_run.id }}
          PREVIOUS_SUITE_ID: ${{ github.event.workflow_run.check_suite_id }}
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
        run: |

          # get artifact id
          while true; do
            ARTIFACT_ID=$(gh api "/repos/$OWNER/$REPO/actions/runs/$PREVIOUS_JOB_ID/artifacts" --jq ".artifacts[0].id")
            if [ -n "$ARTIFACT_ID" ]; then break; fi
            # the artifact isn't available immediately, retry
            echo No artifact, will retry shortly
            sleep 10
          done
          echo "ARTIFACT ID: $ARTIFACT_ID"

          # post link comment
          gh api "/repos/$OWNER/$REPO/issues/$PR_NUMBER/comments" -F body=@- <<EOF
          [Download testing apk](https://github.com/$OWNER/$REPO/suites/$PREVIOUS_SUITE_ID/artifacts/$ARTIFACT_ID)
          This unsigned apk can be installed alongside the original app and should only be used for testing the changes, not for normal usage.
          The link may expire in 90 days.
          EOF